# Generated by Django 2.1.4 on 2018-12-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDiscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cooking_date', models.DateTimeField(help_text='Please enter the date the food was made here')),
                ('expiry_date', models.DateTimeField(help_text='Please enter the date the food is expected to expire')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('type', models.CharField(choices=[('V', 'Vegitarian'), ('N', 'NonVegitarian')], max_length=7)),
            ],
        ),
    ]
